# Generated by Django 2.2.7 on 2019-11-22 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('firstname', models.CharField(db_column='firstName', max_length=45)),
                ('lastname', models.CharField(db_column='lastName', max_length=45)),
                ('ssn', models.CharField(db_column='SSN', max_length=11, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'employees',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('hotelid', models.IntegerField(db_column='HotelID', primary_key=True, serialize=False)),
                ('stars', models.IntegerField(blank=True, null=True)),
                ('numofrooms', models.IntegerField(blank=True, db_column='NumOfRooms', null=True)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=45, null=True)),
                ('location', models.CharField(blank=True, db_column='Location', max_length=45, null=True)),
            ],
            options={
                'db_table': 'hotels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('reservationid', models.AutoField(db_column='reservationID', primary_key=True, serialize=False)),
                ('startdate', models.DateField(db_column='startDate')),
                ('enddate', models.DateField(db_column='endDate')),
                ('firstname', models.CharField(db_column='firstName', max_length=45)),
                ('lastname', models.CharField(db_column='lastName', max_length=45)),
                ('creditcardnum', models.CharField(db_column='creditCardNum', max_length=45)),
                ('phonenum', models.CharField(db_column='phoneNum', max_length=45)),
            ],
            options={
                'db_table': 'reservations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
            ],
            options={
                'db_table': 'rooms',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('reservationid', models.ForeignKey(db_column='reservationID', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='booking.Reservations')),
                ('firstname', models.CharField(db_column='firstName', max_length=45)),
                ('lastname', models.CharField(db_column='lastName', max_length=45)),
            ],
            options={
                'db_table': 'guests',
                'managed': False,
            },
        ),
    ]
